name: Load Dataset artifact to wandb

on:
  push:
    branches:
      - main
    paths:
      - 'src/load.py'

jobs:
  load_data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Login to WandB
      run: wandb login ${{ secrets.WANDB_API_KEY }}
    - name: Run load.py
      run: python src/load.py --IdExecution ${{ github.run_number }}
